### ISSUE TITLE
Stream consumer not starting 

### ISSUE THREAD

**Issue by sulphur** [jacklund/kafka_ex#31]
Do you guys have some guidelines for creating the consumer. I spotted that when i lunch a consumer directly on app start it is unable to find the topic. From what i succeed to see it might be linked to the fact that it can't find a broker. In ```KafkaEx.Protocol.ConsumerMetadata``` on line 7 the ```consumer_group_metadata.coordinator_host``` is nil

If i create a GenServer after few seconds and launch the consumer after some time i suceed to consume the messages. So should i delalay the start of the consumer or maybe it is linked to something i didn't do ? ( I basically followed the readme to create a stream consumer)

**Comment by sulphur** [comment]
For example is there a way to know when the worker got all the information and is capable of streaming ?

**Comment by bjhaid** [comment]
What version of kafka are you running?
How do you launch your consumer?
If you try `Kafka.fetch/3` do you get the same problems?

I don't think it has anything to do with consumer_groups if there is no `coordinator_host` it shouldn't stop the consumer from getting messages, the only explanation I have is that there is no message to consume and the worker would keep retrying sleeping 500ms in between retries.

**Comment by sulphur** [comment]
With KafkaEx.fetch it works great. I actually finished by doing my consumers with fetch method and it works good. 
I have another problem then When one of my brokers is going down (i kill it) the kafka_ex app is shutting down. I think it should restart itself or is it volontary ?

**Comment by bjhaid** [comment]
If `KafkaEx.fetch` works `KafkaEx.stream` should work, they are doing about the same thing under the covers

If you have a cluster of brokers, when you take one out, `kafka_ex` should smartly detect that it is down, with help from `kafka` and it would not talk to it anyone, however if your entire cluster is down (or you have only one broker), the worker would fail, the supervisor would try restarting it several times, and it would still fail, so the app would shutdown, it's all Erlang supervision happening there.

**Comment by sulphur** [comment]
In my case i have 3 brokres on my local machine. I'm running a consumers in tasks processes that are using KafkaEx.fetch

For instance if i do this in console : 
```iex(14)> KafkaEx.fetch("k_users",2,[offset: 775, worker_name: :pr])```

I got following error if leader for partition 2 is down :

```
** (exit) exited in: GenServer.call(:pr, {:fetch, "k_users", 2, 775, 10, 1, 1000000, true}, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in KafkaEx.Protocol.Fetch.parse_response/1
            (kafka_ex) lib/kafka_ex/protocol/fetch.ex:18: KafkaEx.Protocol.Fetch.parse_response(nil)
            (kafka_ex) lib/kafka_ex/server.ex:241: KafkaEx.Server.fetch/8
            (kafka_ex) lib/kafka_ex/server.ex:50: KafkaEx.Server.handle_call/3
            (stdlib) gen_server.erl:607: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:639: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:356: GenServer.call/3
iex(14)> 
10:46:31.111 [error] GenServer :pr terminating
Last message: {:fetch, "k_users", 2, 775, 10, 1, 1000000, true}
State: %KafkaEx.Server{brokers: [%KafkaEx.Protocol.Metadata.Broker{host: "192.168.1.88", node_id: 1, port: 9092, socket: #Port<0.9732>}, %KafkaEx.Protocol.Metadata.Broker{host: "192.168.1.88", node_id: 2, port: 9093, socket: #Port<0.9731>}, %KafkaEx.Protocol.Metadata.Broker{host: "192.168.1.88", node_id: 3, port: 9094, socket: #Port<0.9730>}], consumer_group: "kafka_ex", consumer_metadata: %KafkaEx.Protocol.ConsumerMetadata.Response{coordinator_host: "192.168.1.88", coordinator_id: 2, coordinator_port: 9093, error_code: 0}, correlation_id: 16, event_pid: nil, metadata: %KafkaEx.Protocol.Metadata.Response{brokers: [%KafkaEx.Protocol.Metadata.Broker{host: "192.168.1.88", node_id: 3, port: 9094, socket: nil}, %KafkaEx.Protocol.Metadata.Broker{host: "192.168.1.88", node_id: 2, port: 9093, socket: nil}, %KafkaEx.Protocol.Metadata.Broker{host: "192.168.1.88", node_id: 1, port: 9092, socket: nil}], topic_metadatas: [%KafkaEx.Protocol.Metadata.TopicMetadata{error_code: 0, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 18, replicas: [3, 2, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 0, replicas: [3, 2, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 9, replicas: [3, 1, 2]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 28, replicas: [1, 2, 3]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 41, replicas: [2, 3, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 36, replicas: [3, 2, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 31, replicas: [1, 3, 2]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 19, replicas: [1, 3, 2]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 14, replicas: [2, 1, 3]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 32, replicas: [2, 1, 3]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 22, replicas: [1, 2, 3]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 27, replicas: [3, 1, 2]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 34, replicas: [1, 2, 3]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 2, replicas: [2, 1, 3]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 39, replicas: [3, 1, 2]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 25, replicas: [1, 3, 2]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 20, replicas: [2, 1, 3]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 30, replicas: [3, 2, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 47, replicas: [2, 3, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 43, replicas: [1, 3, 2]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 6, replicas: [3, 2, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 38, replicas: [2, 1, 3]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 46, replicas: [1, 2, 3]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 1, replicas: [1, 3, 2]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 33, replicas: [3, 1, 2]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 29, replicas: [2, 3, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 13, replicas: [1, 3, 2]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 24, replicas: [3, 2, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 4, replicas: [1, 2, 3]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 26, replicas: [2, 1, 3]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 42, replicas: [3, 2, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 37, replicas: [1, 3, 2]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 17, replicas: [2, 3, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 12, replicas: [3, 2, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 49, replicas: [1, 3, ...]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 7, replicas: [1, ...]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 44, ...}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, ...], leader: 1, ...}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [...], ...}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, ...}, %KafkaEx.Protocol.Metadata.PartitionMetadata{...}, ...], topic: "__consumer_offsets"}, %KafkaEx.Protocol.Metadata.TopicMetadata{error_code: 0, partition_metadatas: [%KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [1, 2], leader: 1, partition_id: 0, replicas: [1, 3, 2]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 2, replicas: [3, 2, 1]}, %KafkaEx.Protocol.Metadata.PartitionMetadata{error_code: 0, isrs: [2, 1], leader: 2, partition_id: 1, replicas: [2, 1, 3]}], topic: "k_users"}]}}
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in KafkaEx.Protocol.Fetch.parse_response/1
        (kafka_ex) lib/kafka_ex/protocol/fetch.ex:18: KafkaEx.Protocol.Fetch.parse_response(nil)
        (kafka_ex) lib/kafka_ex/server.ex:241: KafkaEx.Server.fetch/8
        (kafka_ex) lib/kafka_ex/server.ex:50: KafkaEx.Server.handle_call/3
        (stdlib) gen_server.erl:607: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:639: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3

10:46:31.111 [info]  Application kafka_ex exited: shutdown
 ``` 

And after that kafka_en is shut down and i cannot restart is (i need to re-launch iex)

**Comment by bjhaid** [comment]
@sulphur this is a bug, we would fix, I would get back to you once it is fixed

**Comment by bjhaid** [comment]
@sulphur this is fixed, we would coordinate a new release for this, thanks for catching this

**Comment by sulphur** [comment]
cool thank you.
